<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.864" timestamp="2024-01-05T17:58:28.711230" hostname="fv-az802-323"><testcase classname="" name="test.test_image_utils" time="0.000"><error message="collection failure">ImportError while importing test module '/home/runner/work/idss-engine-commons/idss-engine-commons/python/idsse_common/test/test_image_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_image_utils.py:17: in &lt;module&gt;
    from idsse.common.image_utils import GeoImage
idsse/common/image_utils.py:17: in &lt;module&gt;
    from PIL import Image
E   ModuleNotFoundError: No module named 'PIL'</error></testcase></testsuite></testsuites>